export { default as Header } from './header/header'
export { default as About } from './about/about'
export { default as Project } from './project/project'
export { default as Contact } from './contact/contact'
export { default as Skills } from './skills/skills'
export { default as Footer } from './footer/footer'
